import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { gzipSync } from 'node:zlib';

const read = path => JSON.parse(readFileSync(new URL(path,import.meta.url)));
const data=read('results/full.json'),diagnostic=read('results/diagnostic.json');
if(!data.completedAt)throw new Error('Full benchmark has not completed');
const verification=read('results/verification.json');
assert.ok(verification.checks.every(c=>c.exitCode===0),'Verification is incomplete');
const incidentPath=new URL('results/transport-incident.json',import.meta.url);
const rawIncident=existsSync(incidentPath)?read('results/transport-incident.json'):undefined;
const incident=rawIncident&&rawIncident.evidence.inspectedAt>=data.startedAt&&rawIncident.evidence.inspectedAt<=data.completedAt?rawIncident:undefined;
const fixed=x=>Number(x).toFixed(0),seconds=x=>(x/1000).toFixed(2),mean=(rows,field)=>rows.reduce((sum,r)=>sum+(r.metrics[field]??0),0)/rows.length;
const row=(name,label)=>{const s=data.summaries[name];return `| ${label} | ${s.count} | ${seconds(s.p50Ms)} | ${seconds(s.p95Ms)} | ${seconds(s.maxMs)} | ${s.meanRestoreCalls.toFixed(1)} |`;};
const bundle=readFileSync(new URL('.generated/worker.js',import.meta.url));
const ledger=JSON.parse(readFileSync(new URL(`.generated/fixtures/${data.primaryEra}-8-late.json`,import.meta.url))).record;
const burstRows=kind=>data.bursts.filter(b=>b.stage===kind);
const array=rows=>rows.map(r=>fixed(r.clientMs)).join(', ');
const keys=['warm-snapshot','spin','respin','lock','submit','final-submit','stale','retry'];
const table=[row('primary/8/late/warm-snapshot','Late snapshot'),...keys.slice(1).map(k=>row(`primary/8/late/${k}`,k)),
  row('primary/8/late/cold-snapshot','Cold late snapshot'),row('primary/8/late/cold-spin','Cold SPIN'),
  row('primary/8/resolved/cold-snapshot','Cold resolved snapshot'),row('primary/8/late/process-cold-snapshot','Process-cold snapshot'),
  row('primary/8/burst-spin','Burst SPIN — all clients'),row('primary/8/burst-lock','Burst LOCK — all clients'),
  row('primary/8/deadline/overdue-cold','Overdue cold recovery'),row('primary/8/deadline/resolved-snapshot','Post-alarm result read')].join('\n');
const meets = (name, p95, maximum) => data.summaries[name].p95Ms <= p95 && data.summaries[name].maxMs <= maximum;
for (const n of [2,8]) for (const stage of ['early','middle','late','resolved']) assert.equal(data.samples[`primary/${n}/${stage}/warm-snapshot`].length,30);
for (const name of keys.slice(1)) assert.equal(data.samples[`primary/8/late/${name}`].length,30);
for (const name of ['primary/8/late/cold-snapshot','primary/8/resolved/cold-snapshot','primary/8/late/cold-spin','primary/8/deadline/overdue-cold']) assert.equal(data.samples[name].length,20);
assert.equal(data.samples['primary/8/late/process-cold-snapshot'].length,5);
assert.equal(data.bursts.length,40); assert.equal(data.deadlines.length,20); assert.equal(data.checks.length,5);
for (const kind of ['spin','lock']) assert.equal(data.samples[`primary/8/burst-${kind}`].length,160);
const gates={warmSnapshot:meets('primary/8/late/warm-snapshot',500,1000),
  warmCommands:['spin','respin','lock','submit','stale','retry'].every(k=>meets(`primary/8/late/${k}`,500,1000)),
  cold:['primary/8/late/cold-snapshot','primary/8/resolved/cold-snapshot','primary/8/late/cold-spin','primary/8/late/process-cold-snapshot','primary/8/deadline/overdue-cold'].every(k=>meets(k,1500,3000)),
  bursts:['spin','lock'].every(k=>meets(`primary/8/burst-${k}`,2000,3000)),
  final:meets('primary/8/late/final-submit',2000,3000),
  deadlineResolution:data.deadlines.every(d=>d.deadlineToCompletionMs<=3000)&&[...data.deadlines].sort((a,b)=>a.deadlineToCompletionMs-b.deadlineToCompletionMs)[18].deadlineToCompletionMs<=2000};
const decision=Object.values(gates).every(Boolean)?'GO':'HOLD';
const phases=keys.slice(1).map(k=>{const r=data.samples[`primary/8/late/${k}`];return `| ${k} | ${fixed(mean(r,'restoreMs'))} | ${fixed(mean(r,'reduceMs'))} | ${fixed(mean(r,'storageReadMs'))} | ${fixed(mean(r,'storageWriteMs'))} | ${fixed(mean(r,'serializeMs'))} |`;}).join('\n');
const hot=diagnostic.hottestSelfSamples.find(r=>r.functionName==='evaluateFutureCompletion');
let text=`# Draft-Off M4 Stage A report — ${decision}\n\n`;
text+=`Completed ${data.completedAt} (UTC). Main fixture: **${data.primaryEra}, eight participants, ten locked picks each**, with distinct deterministic XIs and complete historical receipt ledgers. All product durations remain 10/15 minutes, default 15. Retired-code markers are bounded to 30 days after cleanup; no lifecycle implementation is included in Stage A.\n\n`;
text+=`## Decision\n\n**${decision} for Stages B–E.** The Worker/one-Durable-Object architecture remains appropriate, but the unchanged replay path does not meet timed-drafting responsiveness. No deployment or later M4 stage has started. M1–M3 and the root dependency files are unchanged.\n\n`;
text+=`Local correctness passes do not override product latency failures. Gate results: ${Object.entries(gates).map(([k,v])=>`${k}=${v?'PASS':'FAIL'}`).join(', ')}.\n\n`;
text+=`## Artifact selection and runtime\n\n| Era | Raw bytes | gzip bytes | Profiles | Team-seasons | Opponents | Late snapshot smoke median (s) |\n|---|---:|---:|---:|---:|---:|---:|\n`;
text+=data.inventory.map(e=>`| ${e.eraId} | ${e.sizeBytes} | ${e.gzipBytes} | ${e.counts.eligibleProfiles} | ${e.counts.teamSeasons} | ${e.counts.opponents} | ${seconds(data.summaries[`${e.eraId}/8/late/warm-snapshot`].p50Ms)} |`).join('\n')+'\n\n';
text+=`The size leader also had the slowest measured replay. Expanded near-equal eras: ${data.expandedEras.length?data.expandedEras.join(', '):'none'}. Each era passed final contested resolution, native object-cold equality, and exact command retry smoke checks. Smoke samples are small and used only for fixture selection.\n\n`;
text+=`Machine: ${data.environment.cpu}, ${data.environment.cpuCount} cores, ${(data.environment.memoryBytes/2**30).toFixed(0)} GiB RAM, ${data.environment.platform}/${data.environment.arch}, OS ${data.environment.osRelease}, Node ${data.environment.node}. Pinned versions: Miniflare 5.20261001.0-alpha / workerd 1.20261001.1 / esbuild 0.28.1; compatibility date 2026-10-01. The alpha Miniflare version is used only by the local harness, not recommended as a production dependency.\n\n`;
text+=`Worker bundle: ${bundle.length} bytes raw / ${gzipSync(bundle).length} gzip. Only the selected era is parsed and verified per object; the five raw artifact strings are bundled. Late canonical save: ${Buffer.byteLength(ledger.serializedCompetition)} bytes; ${Object.keys(ledger.receipts).length} receipts / ${Buffer.byteLength(JSON.stringify(ledger.receipts))} serialized receipt bytes. No filesystem catalog loader or test-support module enters the bundle.\n\n`;
text+=`The run was paused at the user’s request after the warm and cold-snapshot rows, then resumed without repeating completed rows. Resume metadata: ${(data.resumeHistory ?? []).map(h=>`${h.resumedAt} (${h.reason})`).join('; ')}. New raw samples identify their run segment; hardware, OS, Node, and artifact inventory were checked for equality.\n\n`;
text+=`## HTTP latency measurements\n\nTimes are seconds, through the loopback Worker → Durable Object → M3 boundary. p95 uses nearest-rank; cold sets are directional, not production-grade confidence.\n\n| Operation | Samples | Median (s) | p95 (s) | Max (s) | Mean restore calls |\n|---|---:|---:|---:|---:|---:|\n${table}\n\n`;
text+=`| Room/history | Samples | Median (s) | p95 (s) | Max (s) | Mean restore calls |\n|---|---:|---:|---:|---:|---:|\n`;
text+=[2,8].flatMap(n=>['early','middle','late','resolved'].map(stage=>row(`primary/${n}/${stage}/warm-snapshot`,`${n} players / ${stage}`))).join('\n')+'\n\n';
text+=`## Eight-player queueing and timed drafting\n\nEvery one of the 20 trials submits eight independent SPIN requests together, then eight valid LOCK requests together, with each trial starting from the same late fixture. All accepted; no room-revision collision was imposed on independent drafts.\n\n`;
for(const kind of ['spin','lock']){const b=burstRows(kind),first=b.map(x=>Math.min(...x.participants.map(p=>p.clientMs))),last=b.map(x=>Math.max(...x.participants.map(p=>p.clientMs)));
  text+=`- ${kind}: first-client range ${seconds(Math.min(...first))}–${seconds(Math.max(...first))} s; last-client range ${seconds(Math.min(...last))}–${seconds(Math.max(...last))} s; maximum total drain ${seconds(Math.max(...b.map(x=>x.drainMs)))} s.\n`;
}
const recoveredBurstRequests=data.bursts.flatMap(b=>b.participants).filter(p=>p.metrics.resumeMs>0).length;
const switchedPhaseTrials=data.bursts.filter(b=>b.stage==='spin').filter(b=>{const lock=data.bursts.find(l=>l.stage==='lock'&&l.trial===b.trial);return lock&&b.participants.at(-1).instanceId!==lock.participants[0].instanceId;}).length;
text+=`\n${recoveredBurstRequests} measured burst requests included service reconstruction; ${switchedPhaseTrials} trials changed object instance between SPIN and LOCK without explicit eviction there. Native instance IDs and resume timings are preserved. These observations reinforce that a warm-only cache would be insufficient; the reason for automatic re-instantiation is not inferred.\n`;
text+=`\nThe slowest client must await serial authoritative work. This is visible interaction delay, and back-to-back spin/lock bursts consume a meaningful portion of a ten-minute round. Optimistic animations or WebSockets cannot make authoritative selection/legality responses arrive sooner. A command queued near the deadline still receives its execution timestamp under M3, so it can become too late while waiting; that rule remains unchanged.\n\n`;
const clientGroups=new Map();
for(const b of data.bursts){const driver=b.participants[0].clientDriver??'fetch/Undici';const key=`${driver} / ${b.stage}`;const group=clientGroups.get(key)??[];group.push(...b.participants.map(p=>p.clientMs));clientGroups.set(key,group);}
text+=`## HTTP client segments and failed attempt\n\nBoth drivers use independent loopback HTTP connections and measure through the full response body. Node built-in HTTP uses agent:false and performs no application retries. They are shown separately because the client implementation changed after a local socket failure.\n\n| Client/action | Successful responses | Median (s) | Directional p95 (s) | Max (s) |\n|---|---:|---:|---:|---:|\n`;
for(const[key,values]of clientGroups){values.sort((a,b)=>a-b);text+=`| ${key} | ${values.length} | ${seconds(values[Math.ceil(values.length*.5)-1])} | ${seconds(values[Math.ceil(values.length*.95)-1])} | ${seconds(values.at(-1))} |\n`;}
if(incident)text+=`\nOne additional partial burst attempt failed with a local socket closing before any response bytes for participant p7. After teardown/restart, all eight SPIN receipts and only LOCK receipts p0–p3 were present; p7 had not committed. Its uncaptured failure duration is excluded from successful-trial percentiles, and the attempt is explicitly retained in transport-incident.json. The cause remains unresolved; this is not evidence of a production Cloudflare failure rate. The client driver was changed, and the remaining trials resumed from clean fixtures. No domain or provider adapter optimization was applied.\n\n`;
text+=`## Attribution and resource observations\n\nWarm mean phase timings (ms); service resume is an overlapping aggregate and excluded from this sum.\n\n| Command | Restore/replay | Reduce | Storage read/hydrate | Storage write/alarm | Canonical serialize |\n|---|---:|---:|---:|---:|---:|\n${phases}\n\n`;
text+=`A separate inspector diagnostic measured ${diagnostic.profileDurationMs.toFixed(0)} ms with ${diagnostic.sampleCount} CPU samples. evaluateFutureCompletion accounts for approximately ${(hot.selfSampleMs/diagnostic.profileDurationMs*100).toFixed(1)}% of sampled elapsed time (${hot.selfSampleMs.toFixed(0)} ms of self samples). The source rescans all era player variants and, when a keeper is still needed, repeatedly sorts completion costs for each keeper. Replay repeats these checks inside existing invariants and selection validation. Database latency and the new simulation transition are comparatively small.\n\n`;
text+=`Inspector live heap observations: ${(diagnostic.heapBefore.usedSize/2**20).toFixed(1)} MiB before / ${(diagnostic.heapAfter.usedSize/2**20).toFixed(1)} MiB after diagnostic SPIN. Allocated heap after: ${(diagnostic.heapAfter.totalSize/2**20).toFixed(1)} MiB. These are samples, not a peak bound, and do not establish production memory headroom or CPU-quota compliance. All requests in the 20 reported successful burst trials completed; an additional failed partial attempt is documented above. Unforced object re-instantiation during bursts is counted above; deliberate eviction and process restart are separate scenarios. The cause and production frequency of automatic eviction are not established by these local samples.\n\n`;
text+=`## Deadlines and recovery\n\n${data.deadlines.length} autonomous alarm trials completed without participant reads triggering resolution; ${data.deadlines.filter(x=>x.cold).length} were object-cold. Polling used an inspection endpoint that never initializes M3. Each saved history contained exactly one FINALIZE_ROUND and a contested result. Repeated resume preserved canonical bytes.\n\n`;
const alarms=data.deadlines.map(d=>d.metrics.serviceMs);text+=`Alarm handler elapsed samples (ms): ${alarms.join(', ')}. Maximum: ${fixed(Math.max(...alarms))} ms. Actual deadline-to-completed-handler samples (ms): ${data.deadlines.map(d=>fixed(d.deadlineToCompletionMs)).join(', ')}. Maximum: ${fixed(Math.max(...data.deadlines.map(d=>d.deadlineToCompletionMs)))} ms. Alarm delivery delays (ms): ${data.deadlines.map(d=>fixed(d.alarmDeliveryDelayMs)).join(', ')}. Inspection-based waits additionally include polling, the one-second remaining deadline, and the subsequent participant result read. ${data.samples['primary/8/deadline/overdue-cold'].length} overdue-cold requests recovered correctly. Five separate workerd restarts retained the same SQLite room and receipts.\n\n`;
text+=`## Underlying cold samples\n\nThese values are request-to-full-body milliseconds, not estimates.\n\n`;
for(const[k,label]of[['primary/8/late/cold-snapshot','Late object-cold snapshot'],['primary/8/resolved/cold-snapshot','Resolved object-cold snapshot'],['primary/8/late/cold-spin','Object-cold SPIN'],['primary/8/late/process-cold-snapshot','Process-cold snapshot'],['primary/8/deadline/overdue-cold','Overdue object-cold recovery']])text+=`- ${label}: ${array(data.samples[k])}.\n`;
text+=`\nProcess startup is excluded from HTTP latency and reported separately (ms): ${data.samples['primary/8/late/process-cold-snapshot'].map(s=>fixed(s.runtimeBootMs)).join(', ')}.\n\nAll per-client burst samples, warm arrays, response sizes, phase counts, and timing metadata remain in full.json.\n\n`;
text+=`## Required next action — proposal only\n\nKeep Worker → one room Durable Object → M3 → M2 → M1. No additional infrastructure is indicated. A focused provider-independent performance pass is required before B–E:\n\n1. First replace repeated binary-cost sorting in evaluateFutureCompletion with equivalent domestic/overseas counts. Costs are only zero or one: for each remaining keeper, its cost plus the minimum cost of the other slots can be calculated without rebuilding and sorting all other players. Preserve the existing scan initially, including UNKNOWN fail-closed errors, all fields, and sorted keeper ordering. Prove equivalence across all eras, partial XIs, player/season variants, and keeper/overseas boundaries. Then measure whether catalog-derived canonical-player cost indexes are still needed.\n2. If necessary after that change, add carefully bounded memoization of pure feasibility results or validated immutable states keyed by catalog identity and complete inputs. Never cache mutable caller data, trust unvalidated saves, weaken replay verification, or cache an uncommitted transition. Preserve seeded outcomes, canonical bytes, receipts, and error semantics.\n3. Rerun this unchanged harness and the existing regression/legality/replay/simulation suites. Only reconsider B–E when both warm interaction and eight-player queueing meet the product gate; warm caching alone does not solve cold restoration.\n\nThese optimizations are not implemented. They affect shared Era Draft helpers used by M2 rather than Cloudflare code; they require separate review because solo behavior and frozen contracts must remain identical.\n\n`;
text+=`## Limitations and verification\n\nLocal Apple M5/workerd measurements do not predict production Cloudflare hardware, internet RTT, or multi-room contention. Twenty cold trials and five process starts provide directional distributions only. Loopback results already fail, so no deployment is needed to justify HOLD. Fixture loading is excluded, the normal ledger is included, and no optimized restore/cache variant was substituted.\n\nNative runtime correctness: six tests passed (all-era restore/receipt replay, participant races, rollback including alarms, process restart, overdue exactly-once recovery, and repeated native alarms after resolution). Final root regression and typecheck results are recorded alongside this report. An initial harness storage-path mismatch was detected and fixed before the completed main matrix. Deadline test controls were corrected before alarm measurements to advance elapsed time without finalizing inline. Neither repair changed domain behavior. See verification.json and the accompanying logs for the final checks.\n`;
text+=`\n| Final check | Exit | Tests (where applicable) |\n|---|---:|---:|\n${verification.checks.map(c=>`| ${c.label} | ${c.exitCode} | ${c.testCount??'—'} |`).join('\n')}\n`;
writeFileSync(new URL('results/report.md',import.meta.url),text);
writeFileSync(new URL('results/gate.json',import.meta.url),JSON.stringify({decision,gates},null,2)+'\n');
console.log(`${decision}: report written to results/report.md`);
